name: Build and generate

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build.yml"
      - "gradle/**"
      - "src/**"
      - "build.gradle"
      - "settings.gradle"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Clean build dir
        run: ./gradlew clean --no-daemon

      - name: Package to JAR (with dependencies)
        run: ./gradlew shadowJar --no-daemon

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssg-jar
          path: build/libs/ssg.jar
          retention-days: 1

  generate:
    runs-on: ubuntu-latest
    needs: build
    env:
      SERVER_OUTPUT: /var/www/personal-website

    steps:
      - name: Set up JRE 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: ssg-jar

      - name: Generate static content
        run: java -jar ssg.jar -d ${{ vars.REVERSE_PROXY_DOMAIN }}

      - name: Copy generated content on server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: output/*
          target: ${{ env.SERVER_OUTPUT }}
          rm: true
          strip_components: 1
