name: Build and generate

on:
  push:
    branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Clean build dir
        run: ./gradlew clean --no-daemon

      - name: Package to JAR
        run: ./gradlew fatJar --no-daemon

  ssg:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Generate static content
        run: |
          cd .bin
          java -jar parser.jar

      - name: Move files to page content directory
        run: |
          rm -rf /var/www/personal-website/*
          cp -rT .bin/output /var/www/personal-website
